---
- name: Update packages
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Download angristan's OpenVPN installer script
  get_url:
    url: https://raw.githubusercontent.com/angristan/openvpn-install/master/openvpn-install.sh
    dest: /tmp/openvpn-install.sh
    mode: '0755'

- name: Run the OpenVPN installer in non-interactive mode
  command: >
    /tmp/openvpn-install.sh install
    --port 1194
    --protocol udp
    --dns opendns
    --client myclient
  args:
    creates: /etc/openvpn/server/server.conf
  become: true

- name: Fetch the generated client config from the server
  ansible.builtin.fetch:
    src: "/home/ubuntu/myclient.ovpn"
    dest: "../clients/client.ovpn"
  become: true
